/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 19-10月-2018 19:48:49 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Account]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Admin]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Admin]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_AdminLoginLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_AdminLoginLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_AdminOperationLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_AdminOperationLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_ChannelGroup]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_ChannelGroup]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Customer]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Customer]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_CustomerLoginLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_CustomerLoginLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfFailureOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfFailureOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfSetting]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfSetting]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfSuccessOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfSuccessOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_FailureOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_FailureOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Merchant]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Merchant]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_MerchantChannel]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_MerchantChannel]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_MerchantExtend]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_MerchantExtend]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_NotifyTicket]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_NotifyTicket]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Order]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Order]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_PaySetting]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_PaySetting]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Percentage]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Percentage]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_RefundOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_RefundOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_SuccessOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_SuccessOrder]
GO

/* Create Tables */

CREATE TABLE [T_Account]
(
	[Id] bigint NOT NULL,    -- 账号Id
	[FName] varchar(50) NOT NULL,
	[FPassword] varchar(32) NOT NULL,
	[FEmai] varchar(50) NULL,
	[FType] int NOT NULL,
	[FSecretProblem] int NOT NULL,
	[FSecretAnswer] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Admin]
(
	[FAccountId] bigint NOT NULL,    -- 账号Id
	[FJobNumber] int NOT NULL,    -- 工号
	[FFirstLoginIp] varchar(32) NULL,    -- 第一次登陆IP
	[FlastLoginIp] varchar(32) NULL,    -- 最后一次登陆IP
	[FFirstLoginTime] datetime NOT NULL,    -- 第一次登陆时间
	[FLastLoginTime] datetime NOT NULL,    -- 最后一次登陆时间
	[FCreateTime] datetime NOT NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_AdminLoginLog]
(
	[FAccountId] bigint NOT NULL,
	[FLoginIP] varchar(20) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_AdminOperationLog]
(
	[FAccountId] bigint NOT NULL,
	[FLogType] int NOT NULL,
	[FLogContent] varchar(1024) NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_ChannelGroup]
(
	[Id] bigint NOT NULL,
	[FGroupName] varchar(50) NOT NULL,    -- 分组名
	[FGroupType] bigint NOT NULL,    -- 通道分组类型
	[FChannels] varchar(1024) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Customer]
(
	[FAccountId] bigint NOT NULL,    -- 账号Id
	[FJobNumber] int NOT NULL,    -- 工号
	[FFullName] nvarchar(10) NULL,    -- 姓名
	[FFirstLoginIp] varchar(20) NULL,    -- 第一次登陆IP
	[FLastLoginIp] varchar(20) NULL,    -- 最后一次登陆IP
	[FFirstLoginTime] datetime NOT NULL,    -- 第一次登陆时间
	[FLastLoginTime] datetime NOT NULL,    -- 最后一次登陆时间
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_CustomerLoginLog]
(
	[FAccountId] bigint NOT NULL,
	[FLoginIP] varchar(20) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfFailureOrder]
(
	[FOrderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FFromIP] varchar(20) NULL,
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfOrder]
(
	[FOrderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FFromIP] varchar(20) NULL,
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FState] int NOT NULL,
	[FNotifyUrl] varchar(128) NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfSetting]
(
	[Id] bigint NOT NULL,
	[FSId] varchar(20) NULL,
	[FPrivateKey] varchar(2048) NULL,
	[FPublicKey] varchar(1024) NULL,
	[FPayType] int NOT NULL,
	[FEmail] varchar(64) NULL,
	[FRedirectUrl] varchar(256) NULL,
	[FExtened] varchar(256) NULL,
	[FLastInfo] varchar(max) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfSuccessOrder]
(
	[FOderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FState] bit NOT NULL,
	[FFromIP] varchar(20) NULL,
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FNotifyState] int NOT NULL,
	[FNotifyUrl] varchar(128) NOT NULL,
	[FAlipayId] varchar(10) NULL,
	[FPercentage] decimal(18) NOT NULL,
	[FFrozenTime] datetime NULL,
	[FFrozenState] int NOT NULL,
	[FRefundState] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_FailureOrder]
(
	[FOrderNum] bigint NOT NULL,    -- 订单号
	[FMOrderNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户Id
	[FFromIP] varchar(20) NULL,    -- 支付IP
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,    -- 订单金额
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Merchant]
(
	[FAccountId] bigint NOT NULL,
	[FMerchantNumber] int NOT NULL,    -- 商户号
	[FPayeeName] nvarchar(20) NULL,    -- 收款人姓名
	[FBankName] nvarchar(20) NULL,    -- 开户行
	[FBankCard] varchar(18) NULL,    -- 开户银行账号
	[FBankAddress] varchar(32) NULL,    -- 开户银行支行
	[FAmountTotal] decimal(18) NOT NULL,    -- 结算总额
	[FState] int NULL,    -- 商户状态
	[FWithdrawPwd] varchar(6) NOT NULL,    -- 提现密码
	[FRSA2Key] varchar(2048) NOT NULL,    -- 商户应用RSA2私钥
	[FRecvNotifyUrl] varchar(256) NULL,    -- 商户接收通知地址
	[FSyncJumpUrl] bit NOT NULL,    -- 是否同步跳转
	[FDFUserGroup] int NOT NULL,    -- 代付用户组
	[FCreateTime] datetime NULL,
	[FCreateBy] int NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] int NULL
)
GO

CREATE TABLE [T_MerchantChannel]
(
	[FAccountId] bigint NOT NULL,
	[FMid] int NOT NULL,
	[FChannels] varchar(1024) NULL,
	[FChannelGroups] varchar(256) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] int NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] int NULL
)
GO

CREATE TABLE [T_MerchantExtend]
(
	[FAccountId] bigint NOT NULL,    -- 账号Id
	[FMId] int NOT NULL,    -- 商户Id
	[FMName] varchar(20) NOT NULL,    -- 商户名
	[FAddress] nvarchar(128) NULL,    -- 商户地址
	[FId_card] varchar(20) NULL,    -- 商户身份证号码
	[FFullName] nvarchar(20) NULL,    -- 商户姓名
	[FPhone] varchar(20) NULL,    -- 商户电话
	[FMobile] varchar(20) NULL,    -- 手机号码
	[FPostcode] varchar(8) NULL,    -- 邮政编码
	[FStieUrl] varchar(128) NULL,    -- 商户网址
	[FQQ] varchar(16) NULL,    -- QQ账号
	[FMSN] varchar(32) NULL,    -- MSN账号
	[FLastLoginIp] varchar(20) NULL,    -- 最后登陆IP地址
	[FLastLoginTime] datetime NULL,    -- 最后一次登陆时间
	[FWithdrawPwd] varchar(6) NOT NULL,    -- 提现密码
	[FRemark] varchar(50) NULL,    -- 商户描述
	[FGoogleSecretKey] varchar(32) NULL,    -- 谷哥验证器密钥
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_NotifyTicket]
(
	[Id] bigint NOT NULL,
	[FOrderNum] bigint NOT NULL,
	[FState] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Order]
(
	[FOrderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户ID
	[FFromIP] varchar(20) NULL,    -- 支付IP
	[FChannelType] int NOT NULL,    -- 通道类型
	[FChannelCode] varchar(20) NOT NULL,    -- 通道代码
	[FAmount] decimal(18) NOT NULL,    -- 订单金额
	[FState] int NOT NULL,    -- 订单状态
	[FNotifyUrl] varchar(128) NOT NULL,    -- 通知地址
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] int NULL
)
GO

CREATE TABLE [T_PaySetting]
(
	[Id] bigint NOT NULL,
	[FSId] varchar(20) NULL,
	[FPrivateKey] varchar(2048) NULL,    -- 应用私钥，用于加签提交支付参数
	[FPublicKey] varchar(1024) NULL,    -- 第三方平台公钥，用于验签第三方回调通知参数
	[FPayType] int NOT NULL,
	[FEmail] varchar(64) NULL,    -- 邮箱地址
	[FRedirectUrl] varchar(256) NULL,    -- 重定向地址
	[FExtened] varchar(50) NULL,    -- 256个字节字符串扩展字段，用于存放特殊的支付类型Json数据
	[FLastInfo] varchar(max) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Percentage]
(
	[FAccountId] bigint NOT NULL,
	[FPercentage] decimal(18) NOT NULL,
	[FChannelType] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_RefundOrder]
(
	[FOderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FRefundType] int NOT NULL,
	[FRefundCharge] decimal(18) NOT NULL,
	[FRefundAmount] decimal(18) NOT NULL,    -- 实际退款金额
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_SuccessOrder]
(
	[FOderNum] bigint NOT NULL,    -- 订单号
	[FMOrderNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户Id
	[FState] bit NOT NULL,    -- 订单状态
	[FFromIP] varchar(20) NULL,    -- 支付IP
	[FChannelType] int NOT NULL,    -- 通道类型
	[FChannelCode] varchar(20) NOT NULL,    -- 通道代码
	[FAmount] decimal(18) NOT NULL,    -- 订单金额
	[FNotifyState] bit NOT NULL,
	[FNotifyUrl] varchar(128) NOT NULL,    -- 通知地址
	[FAlipayId] varchar(10) NULL,    -- 支付宝Id
	[FPercentage] decimal(18) NOT NULL,    -- 订单商户比例
	[FFrozenTime] datetime NULL,    -- 冻结时间
	[FFrozenState] int NOT NULL,    -- 冻结状态
	[FRefundState] int NOT NULL,    -- 退款状态
	[FRefundTime] datetime NULL,    -- 退款时间
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [T_Account] 
 ADD CONSTRAINT [PK_TAccount]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Admin] 
 ADD CONSTRAINT [PK_TAdmin]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_AdminLoginLog] 
 ADD CONSTRAINT [PK_TAdminLoginLog]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_AdminOperationLog] 
 ADD CONSTRAINT [PK_TAdminOperationLog]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_ChannelGroup] 
 ADD CONSTRAINT [PK_T_ChannelGroup]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Customer] 
 ADD CONSTRAINT [PK_TCustomer]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_CustomerLoginLog] 
 ADD CONSTRAINT [PK_TCustomerLoginLog]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_DfFailureOrder] 
 ADD CONSTRAINT [PK_TDFFailureOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [T_DfOrder] 
 ADD CONSTRAINT [PK_T_DfOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [T_DfSetting] 
 ADD CONSTRAINT [PK_TDFSetting]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_DfSuccessOrder] 
 ADD CONSTRAINT [PK_TDFSuccessOrder]
	PRIMARY KEY CLUSTERED ([FOderNum] ASC)
GO

ALTER TABLE [T_FailureOrder] 
 ADD CONSTRAINT [PK_TFailureOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [T_Merchant] 
 ADD CONSTRAINT [PK_TMerchant]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_MerchantChannel] 
 ADD CONSTRAINT [PK_TMerchantChannel]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_MerchantExtend] 
 ADD CONSTRAINT [PK_TMerchantExtend]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_NotifyTicket] 
 ADD CONSTRAINT [PK_T_NotifyTicket]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Order] 
 ADD CONSTRAINT [PK_TOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [T_PaySetting] 
 ADD CONSTRAINT [PK_TPaySetting]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Percentage] 
 ADD CONSTRAINT [PK_TPercentage]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [T_RefundOrder] 
 ADD CONSTRAINT [PK_TRefundOrder]
	PRIMARY KEY CLUSTERED ([FOderNum] ASC)
GO

ALTER TABLE [T_SuccessOrder] 
 ADD CONSTRAINT [PK_T_SuccessOrder]
	PRIMARY KEY CLUSTERED ([FOderNum] ASC)
GO

/* Create Table Comments */


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Account', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '账号表', 'SCHEMA', 'dbo', 'table', 'T_Account' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '账号表', 'SCHEMA', 'dbo', 'table', 'T_Account' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_Account], 'column', [Id]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Admin', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员表', 'SCHEMA', 'dbo', 'table', 'T_Admin' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员表', 'SCHEMA', 'dbo', 'table', 'T_Admin' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_Admin], 'column', [FAccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '工号', 'Schema', [dbo], 'table', [T_Admin], 'column', [FJobNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆IP', 'Schema', [dbo], 'table', [T_Admin], 'column', [FFirstLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆IP', 'Schema', [dbo], 'table', [T_Admin], 'column', [FlastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆时间', 'Schema', [dbo], 'table', [T_Admin], 'column', [FFirstLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [T_Admin], 'column', [FLastLoginTime]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_AdminLoginLog', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员登陆日志', 'SCHEMA', 'dbo', 'table', 'T_AdminLoginLog' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员登陆日志', 'SCHEMA', 'dbo', 'table', 'T_AdminLoginLog' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_AdminOperationLog', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员操作日志', 'SCHEMA', 'dbo', 'table', 'T_AdminOperationLog' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员操作日志', 'SCHEMA', 'dbo', 'table', 'T_AdminOperationLog' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_ChannelGroup', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '通道组', 'SCHEMA', 'dbo', 'table', 'T_ChannelGroup' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '通道组', 'SCHEMA', 'dbo', 'table', 'T_ChannelGroup' 
end

EXEC sp_addextendedproperty 'MS_Description', '分组名', 'Schema', [dbo], 'table', [T_ChannelGroup], 'column', [FGroupName]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道分组类型', 'Schema', [dbo], 'table', [T_ChannelGroup], 'column', [FGroupType]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Customer', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '客服表', 'SCHEMA', 'dbo', 'table', 'T_Customer' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '客服表', 'SCHEMA', 'dbo', 'table', 'T_Customer' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_Customer], 'column', [FAccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '工号', 'Schema', [dbo], 'table', [T_Customer], 'column', [FJobNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '姓名', 'Schema', [dbo], 'table', [T_Customer], 'column', [FFullName]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆IP', 'Schema', [dbo], 'table', [T_Customer], 'column', [FFirstLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆IP', 'Schema', [dbo], 'table', [T_Customer], 'column', [FLastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆时间', 'Schema', [dbo], 'table', [T_Customer], 'column', [FFirstLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [T_Customer], 'column', [FLastLoginTime]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfFailureOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付失败订单', 'SCHEMA', 'dbo', 'table', 'T_DfFailureOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付失败订单', 'SCHEMA', 'dbo', 'table', 'T_DfFailureOrder' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付全部订单', 'SCHEMA', 'dbo', 'table', 'T_DfOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付全部订单', 'SCHEMA', 'dbo', 'table', 'T_DfOrder' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfSetting', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付接口配置', 'SCHEMA', 'dbo', 'table', 'T_DfSetting' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付接口配置', 'SCHEMA', 'dbo', 'table', 'T_DfSetting' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfSuccessOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '成功代付订单', 'SCHEMA', 'dbo', 'table', 'T_DfSuccessOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '成功代付订单', 'SCHEMA', 'dbo', 'table', 'T_DfSuccessOrder' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_FailureOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '失败订单', 'SCHEMA', 'dbo', 'table', 'T_FailureOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '失败订单', 'SCHEMA', 'dbo', 'table', 'T_FailureOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '订单号', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FMOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FFromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FAmount]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Merchant', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户表', 'SCHEMA', 'dbo', 'table', 'T_Merchant' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户表', 'SCHEMA', 'dbo', 'table', 'T_Merchant' 
end

EXEC sp_addextendedproperty 'MS_Description', '商户号', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FMerchantNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '收款人姓名', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FPayeeName]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户行', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FBankName]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户银行账号', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FBankCard]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户银行支行', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FBankAddress]
GO

EXEC sp_addextendedproperty 'MS_Description', '结算总额', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FAmountTotal]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户状态', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FState]
GO

EXEC sp_addextendedproperty 'MS_Description', '提现密码', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FWithdrawPwd]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户应用RSA2私钥', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FRSA2Key]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户接收通知地址', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FRecvNotifyUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '是否同步跳转', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FSyncJumpUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '代付用户组', 'Schema', [dbo], 'table', [T_Merchant], 'column', [FDFUserGroup]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_MerchantChannel', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户通道', 'SCHEMA', 'dbo', 'table', 'T_MerchantChannel' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户通道', 'SCHEMA', 'dbo', 'table', 'T_MerchantChannel' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_MerchantExtend', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户扩展表', 'SCHEMA', 'dbo', 'table', 'T_MerchantExtend' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户扩展表', 'SCHEMA', 'dbo', 'table', 'T_MerchantExtend' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FAccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户名', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FMName]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户地址', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FAddress]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户身份证号码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FId_card]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户姓名', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FFullName]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户电话', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FPhone]
GO

EXEC sp_addextendedproperty 'MS_Description', '手机号码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FMobile]
GO

EXEC sp_addextendedproperty 'MS_Description', '邮政编码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FPostcode]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户网址', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FStieUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', 'QQ账号', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FQQ]
GO

EXEC sp_addextendedproperty 'MS_Description', 'MSN账号', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FMSN]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后登陆IP地址', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FLastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FLastLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '提现密码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FWithdrawPwd]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户描述', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FRemark]
GO

EXEC sp_addextendedproperty 'MS_Description', '谷哥验证器密钥', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FGoogleSecretKey]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_NotifyTicket', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '异步通知记录表', 'SCHEMA', 'dbo', 'table', 'T_NotifyTicket' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '异步通知记录表', 'SCHEMA', 'dbo', 'table', 'T_NotifyTicket' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Order', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '全部订单表', 'SCHEMA', 'dbo', 'table', 'T_Order' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '全部订单表', 'SCHEMA', 'dbo', 'table', 'T_Order' 
end

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [T_Order], 'column', [FMOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户ID', 'Schema', [dbo], 'table', [T_Order], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [T_Order], 'column', [FFromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道类型', 'Schema', [dbo], 'table', [T_Order], 'column', [FChannelType]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道代码', 'Schema', [dbo], 'table', [T_Order], 'column', [FChannelCode]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [T_Order], 'column', [FAmount]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单状态', 'Schema', [dbo], 'table', [T_Order], 'column', [FState]
GO

EXEC sp_addextendedproperty 'MS_Description', '通知地址', 'Schema', [dbo], 'table', [T_Order], 'column', [FNotifyUrl]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_PaySetting', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '支付接口配置', 'SCHEMA', 'dbo', 'table', 'T_PaySetting' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '支付接口配置', 'SCHEMA', 'dbo', 'table', 'T_PaySetting' 
end

EXEC sp_addextendedproperty 'MS_Description', '应用私钥，用于加签提交支付参数', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [FPrivateKey]
GO

EXEC sp_addextendedproperty 'MS_Description', '第三方平台公钥，用于验签第三方回调通知参数', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [FPublicKey]
GO

EXEC sp_addextendedproperty 'MS_Description', '邮箱地址', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [FEmail]
GO

EXEC sp_addextendedproperty 'MS_Description', '重定向地址', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [FRedirectUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '256个字节字符串扩展字段，用于存放特殊的支付类型Json数据', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [FExtened]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Percentage', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户提成比例表', 'SCHEMA', 'dbo', 'table', 'T_Percentage' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户提成比例表', 'SCHEMA', 'dbo', 'table', 'T_Percentage' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_RefundOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '退款订单', 'SCHEMA', 'dbo', 'table', 'T_RefundOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '退款订单', 'SCHEMA', 'dbo', 'table', 'T_RefundOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '实际退款金额', 'Schema', [dbo], 'table', [T_RefundOrder], 'column', [FRefundAmount]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_SuccessOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '成功订单', 'SCHEMA', 'dbo', 'table', 'T_SuccessOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '成功订单', 'SCHEMA', 'dbo', 'table', 'T_SuccessOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '订单号', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FOderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FMOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单状态', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FState]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FFromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道类型', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FChannelType]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道代码', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FChannelCode]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FAmount]
GO

EXEC sp_addextendedproperty 'MS_Description', '通知地址', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FNotifyUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付宝Id', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FAlipayId]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单商户比例', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FPercentage]
GO

EXEC sp_addextendedproperty 'MS_Description', '冻结时间', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FFrozenTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '冻结状态', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FFrozenState]
GO

EXEC sp_addextendedproperty 'MS_Description', '退款状态', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FRefundState]
GO

EXEC sp_addextendedproperty 'MS_Description', '退款时间', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FRefundTime]
GO
