/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-10月-2018 13:34:14 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TAccount]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TAccount]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TAdmin]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TAdmin]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TAdminLoginLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TAdminLoginLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TAdminOperationLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TAdminOperationLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TCustomer]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TCustomer]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TCustomerLoginLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TCustomerLoginLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TDFFailureOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TDFFailureOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TDFOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TDFOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TDFSetting]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TDFSetting]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TDFSuccessOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TDFSuccessOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TFailureOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TFailureOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TMerchant]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TMerchant]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TMerchantChannel]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TMerchantChannel]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TMerchantExtend]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TMerchantExtend]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TPaySetting]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TPaySetting]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TPercentage]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TPercentage]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TRefundOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TRefundOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TSuccessOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TSuccessOrder]
GO

/* Create Tables */

CREATE TABLE [TAccount]
(
	[Id] bigint NOT NULL,    -- 账号Id
	[FName] varchar(50) NOT NULL,
	[FPassword] varchar(32) NOT NULL,
	[FEmai] varchar(50) NULL,
	[FType] int NOT NULL,
	[FSecretProblem] int NOT NULL,
	[FSecretAnswer] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TAdmin]
(
	[FAccountId] bigint NOT NULL,    -- 账号Id
	[FJobNumber] int NOT NULL,    -- 工号
	[FFirstLoginIp] varchar(32) NULL,    -- 第一次登陆IP
	[FlastLoginIp] varchar(32) NULL,    -- 最后一次登陆IP
	[FFirstLoginTime] datetime NOT NULL,    -- 第一次登陆时间
	[FLastLoginTime] datetime NOT NULL,    -- 最后一次登陆时间
	[FCreateTime] datetime NOT NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TAdminLoginLog]
(
	[FAccountId] bigint NOT NULL,
	[FLoginIP] varchar(20) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TAdminOperationLog]
(
	[FAccountId] bigint NOT NULL,
	[FLogType] int NOT NULL,
	[FLogContent] varchar(1024) NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TCustomer]
(
	[FAccountId] bigint NOT NULL,    -- 账号Id
	[FJobNumber] int NOT NULL,    -- 工号
	[FFullName] nvarchar(10) NULL,    -- 姓名
	[FFirstLoginIp] varchar(20) NULL,    -- 第一次登陆IP
	[FLastLoginIp] varchar(20) NULL,    -- 最后一次登陆IP
	[FFirstLoginTime] datetime NOT NULL,    -- 第一次登陆时间
	[FLastLoginTime] datetime NOT NULL,    -- 最后一次登陆时间
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TCustomerLoginLog]
(
	[FAccountId] bigint NOT NULL,
	[FLoginIP] varchar(20) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TDFFailureOrder]
(
	[FOrderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FFromIP] varchar(20) NULL,
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TDFOrder]
(
	[FOrderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FFromIP] varchar(20) NULL,
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FState] int NOT NULL,
	[FNotifyUrl] varchar(128) NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TDFSetting]
(
	[Id] bigint NOT NULL,
	[FSId] varchar(20) NULL,
	[FPrivateKey] varchar(2048) NULL,
	[FPublicKey] varchar(1024) NULL,
	[FPayType] int NOT NULL,
	[FEmail] varchar(64) NULL,
	[FRedirectUrl] varchar(256) NULL,
	[FExtened] varchar(256) NULL,
	[FLastInfo] varchar(max) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TDFSuccessOrder]
(
	[FOderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FState] bit NOT NULL,
	[FFromIP] varchar(20) NULL,
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FNotifyState] int NOT NULL,
	[FNotifyUrl] varchar(128) NOT NULL,
	[FAlipayId] varchar(10) NULL,
	[FPercentage] decimal(18) NOT NULL,
	[FFrozenTime] datetime NULL,
	[FFrozenState] int NOT NULL,
	[FRefundState] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TFailureOrder]
(
	[FOrderNum] bigint NOT NULL,    -- 订单号
	[FMOrderNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户Id
	[FFromIP] varchar(20) NULL,    -- 支付IP
	[FChannelType] int NOT NULL,
	[FChannelCode] varchar(20) NOT NULL,
	[FAmount] decimal(18) NOT NULL,    -- 订单金额
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TMerchant]
(
	[FAccountId] bigint NOT NULL,
	[FMerchantNumber] int NOT NULL,    -- 商户号
	[FPayeeName] nvarchar(20) NULL,    -- 收款人姓名
	[FBankName] nvarchar(20) NULL,    -- 开户行
	[FBankCard] varchar(18) NULL,    -- 开户银行账号
	[FBankAddress] varchar(32) NULL,    -- 开户银行支行
	[FAmountTotal] decimal(18) NOT NULL,    -- 结算总额
	[FState] int NULL,    -- 商户状态
	[FWithdrawPwd] varchar(6) NOT NULL,    -- 提现密码
	[FRSA2Key] varchar(2048) NOT NULL,    -- 商户应用RSA2私钥
	[FRecvNotifyUrl] varchar(256) NULL,    -- 商户接收通知地址
	[FSyncJumpUrl] bit NOT NULL,    -- 是否同步跳转
	[FDFUserGroup] int NOT NULL,    -- 代付用户组
	[FCreateTime] datetime NULL,
	[FCreateBy] int NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] int NULL
)
GO

CREATE TABLE [TMerchantChannel]
(
	[FAccountId] bigint NOT NULL,
	[FMid] int NOT NULL,
	[FChannels] varchar(1024) NULL,
	[FChannelGroups] varchar(256) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] int NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] int NULL
)
GO

CREATE TABLE [TMerchantExtend]
(
	[FAccountId] bigint NOT NULL,    -- 账号Id
	[FMId] int NOT NULL,    -- 商户Id
	[FMName] varchar(20) NOT NULL,    -- 商户名
	[FAddress] nvarchar(128) NULL,    -- 商户地址
	[FId_card] varchar(20) NULL,    -- 商户身份证号码
	[FFullName] nvarchar(20) NULL,    -- 商户姓名
	[FPhone] varchar(20) NULL,    -- 商户电话
	[FMobile] varchar(20) NULL,    -- 手机号码
	[FPostcode] varchar(8) NULL,    -- 邮政编码
	[FStieUrl] varchar(128) NULL,    -- 商户网址
	[FQQ] varchar(16) NULL,    -- QQ账号
	[FMSN] varchar(32) NULL,    -- MSN账号
	[FLastLoginIp] varchar(20) NULL,    -- 最后登陆IP地址
	[FLastLoginTime] datetime NULL,    -- 最后一次登陆时间
	[FWithdrawPwd] varchar(6) NOT NULL,    -- 提现密码
	[FRemark] varchar(50) NULL,    -- 商户描述
	[FGoogleSecretKey] varchar(32) NULL,    -- 谷哥验证器密钥
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TOrder]
(
	[FOrderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户ID
	[FFromIP] varchar(20) NULL,    -- 支付IP
	[FChannelType] int NOT NULL,    -- 通道类型
	[FChannelCode] varchar(20) NOT NULL,    -- 通道代码
	[FAmount] decimal(18) NOT NULL,    -- 订单金额
	[FState] int NOT NULL,    -- 订单状态
	[FNotifyUrl] varchar(128) NOT NULL,    -- 通知地址
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] int NULL
)
GO

CREATE TABLE [TPaySetting]
(
	[Id] bigint NOT NULL,
	[FSId] varchar(20) NULL,
	[FPrivateKey] varchar(2048) NULL,    -- 应用私钥，用于加签提交支付参数
	[FPublicKey] varchar(1024) NULL,    -- 第三方平台公钥，用于验签第三方回调通知参数
	[FPayType] int NOT NULL,
	[FEmail] varchar(64) NULL,    -- 邮箱地址
	[FRedirectUrl] varchar(256) NULL,    -- 重定向地址
	[FExtened] varchar(50) NULL,    -- 256个字节字符串扩展字段，用于存放特殊的支付类型Json数据
	[FLastInfo] varchar(max) NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TPercentage]
(
	[FAccountId] bigint NOT NULL,
	[FPercentage] decimal(18) NOT NULL,
	[FChannelType] int NOT NULL,
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TRefundOrder]
(
	[FOderNum] bigint NOT NULL,
	[FMOrderNum] varchar(64) NOT NULL,
	[FMId] int NOT NULL,
	[FAmount] decimal(18) NOT NULL,
	[FRefundType] int NOT NULL,
	[FRefundCharge] decimal(18) NOT NULL,
	[FRefundAmount] decimal(18) NOT NULL,    -- 实际退款金额
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [TSuccessOrder]
(
	[FOderNum] bigint NOT NULL,    -- 订单号
	[FMOrderNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户Id
	[FState] bit NOT NULL,    -- 订单状态
	[FFromIP] varchar(20) NULL,    -- 支付IP
	[FChannelType] int NOT NULL,    -- 通道类型
	[FChannelCode] varchar(20) NOT NULL,    -- 通道代码
	[FAmount] decimal(18) NOT NULL,    -- 订单金额
	[FNotifyState] bit NOT NULL,
	[FNotifyUrl] varchar(128) NOT NULL,    -- 通知地址
	[FAlipayId] varchar(10) NULL,    -- 支付宝Id
	[FPercentage] decimal(18) NOT NULL,    -- 订单商户比例
	[FFrozenTime] datetime NULL,    -- 冻结时间
	[FFrozenState] int NOT NULL,    -- 冻结状态
	[FRefundState] int NOT NULL,    -- 退款状态
	[FRefundTime] datetime NULL,    -- 退款时间
	[FCreateTime] datetime NULL,
	[FCreateBy] bigint NULL,
	[FUpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [TAccount] 
 ADD CONSTRAINT [PK_TAccount]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [TAdmin] 
 ADD CONSTRAINT [PK_TAdmin]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TAdminLoginLog] 
 ADD CONSTRAINT [PK_TAdminLoginLog]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TAdminOperationLog] 
 ADD CONSTRAINT [PK_TAdminOperationLog]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TCustomer] 
 ADD CONSTRAINT [PK_TCustomer]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TCustomerLoginLog] 
 ADD CONSTRAINT [PK_TCustomerLoginLog]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TDFFailureOrder] 
 ADD CONSTRAINT [PK_TDFFailureOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [TDFOrder] 
 ADD CONSTRAINT [PK_Table1]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [TDFSetting] 
 ADD CONSTRAINT [PK_TDFSetting]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [TDFSuccessOrder] 
 ADD CONSTRAINT [PK_TDFSuccessOrder]
	PRIMARY KEY CLUSTERED ([FOderNum] ASC)
GO

ALTER TABLE [TFailureOrder] 
 ADD CONSTRAINT [PK_TFailureOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [TMerchant] 
 ADD CONSTRAINT [PK_TMerchant]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TMerchantChannel] 
 ADD CONSTRAINT [PK_TMerchantChannel]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TMerchantExtend] 
 ADD CONSTRAINT [PK_TMerchantExtend]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TOrder] 
 ADD CONSTRAINT [PK_TOrder]
	PRIMARY KEY CLUSTERED ([FOrderNum] ASC)
GO

ALTER TABLE [TPaySetting] 
 ADD CONSTRAINT [PK_TPaySetting]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [TPercentage] 
 ADD CONSTRAINT [PK_TPercentage]
	PRIMARY KEY CLUSTERED ([FAccountId] ASC)
GO

ALTER TABLE [TRefundOrder] 
 ADD CONSTRAINT [PK_TRefundOrder]
	PRIMARY KEY CLUSTERED ([FOderNum] ASC)
GO

ALTER TABLE [TSuccessOrder] 
 ADD CONSTRAINT [PK_Table1]
	PRIMARY KEY CLUSTERED ([FOderNum] ASC)
GO

/* Create Table Comments */


GO
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TAccount', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '账号表', 'SCHEMA', 'dbo', 'table', 'TAccount' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '账号表', 'SCHEMA', 'dbo', 'table', 'TAccount' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [TAccount], 'column', [Id]
GO


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TAdmin', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员表', 'SCHEMA', 'dbo', 'table', 'TAdmin' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员表', 'SCHEMA', 'dbo', 'table', 'TAdmin' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [TAdmin], 'column', [FAccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '工号', 'Schema', [dbo], 'table', [TAdmin], 'column', [FJobNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆IP', 'Schema', [dbo], 'table', [TAdmin], 'column', [FFirstLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆IP', 'Schema', [dbo], 'table', [TAdmin], 'column', [FlastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆时间', 'Schema', [dbo], 'table', [TAdmin], 'column', [FFirstLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [TAdmin], 'column', [FLastLoginTime]
GO


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TAdminLoginLog', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员登陆日志', 'SCHEMA', 'dbo', 'table', 'TAdminLoginLog' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员登陆日志', 'SCHEMA', 'dbo', 'table', 'TAdminLoginLog' 
end


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TAdminOperationLog', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员操作日志', 'SCHEMA', 'dbo', 'table', 'TAdminOperationLog' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员操作日志', 'SCHEMA', 'dbo', 'table', 'TAdminOperationLog' 
end


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TCustomer', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '客服表', 'SCHEMA', 'dbo', 'table', 'TCustomer' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '客服表', 'SCHEMA', 'dbo', 'table', 'TCustomer' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [TCustomer], 'column', [FAccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '工号', 'Schema', [dbo], 'table', [TCustomer], 'column', [FJobNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '姓名', 'Schema', [dbo], 'table', [TCustomer], 'column', [FFullName]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆IP', 'Schema', [dbo], 'table', [TCustomer], 'column', [FFirstLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆IP', 'Schema', [dbo], 'table', [TCustomer], 'column', [FLastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆时间', 'Schema', [dbo], 'table', [TCustomer], 'column', [FFirstLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [TCustomer], 'column', [FLastLoginTime]
GO


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TDFFailureOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付失败订单', 'SCHEMA', 'dbo', 'table', 'TDFFailureOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付失败订单', 'SCHEMA', 'dbo', 'table', 'TDFFailureOrder' 
end


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TDFOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付全部订单', 'SCHEMA', 'dbo', 'table', 'TDFOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付全部订单', 'SCHEMA', 'dbo', 'table', 'TDFOrder' 
end


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TDFSetting', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付接口配置', 'SCHEMA', 'dbo', 'table', 'TDFSetting' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付接口配置', 'SCHEMA', 'dbo', 'table', 'TDFSetting' 
end


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TDFSuccessOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '成功代付订单', 'SCHEMA', 'dbo', 'table', 'TDFSuccessOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '成功代付订单', 'SCHEMA', 'dbo', 'table', 'TDFSuccessOrder' 
end


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TFailureOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '失败订单', 'SCHEMA', 'dbo', 'table', 'TFailureOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '失败订单', 'SCHEMA', 'dbo', 'table', 'TFailureOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '订单号', 'Schema', [dbo], 'table', [TFailureOrder], 'column', [FOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [TFailureOrder], 'column', [FMOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [TFailureOrder], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [TFailureOrder], 'column', [FFromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [TFailureOrder], 'column', [FAmount]
GO


GO
 if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TMerchant', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户表', 'SCHEMA', 'dbo', 'table', 'TMerchant' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户表', 'SCHEMA', 'dbo', 'table', 'TMerchant' 
end

EXEC sp_addextendedproperty 'MS_Description', '商户号', 'Schema', [dbo], 'table', [TMerchant], 'column', [FMerchantNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '收款人姓名', 'Schema', [dbo], 'table', [TMerchant], 'column', [FPayeeName]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户行', 'Schema', [dbo], 'table', [TMerchant], 'column', [FBankName]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户银行账号', 'Schema', [dbo], 'table', [TMerchant], 'column', [FBankCard]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户银行支行', 'Schema', [dbo], 'table', [TMerchant], 'column', [FBankAddress]
GO

EXEC sp_addextendedproperty 'MS_Description', '结算总额', 'Schema', [dbo], 'table', [TMerchant], 'column', [FAmountTotal]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户状态', 'Schema', [dbo], 'table', [TMerchant], 'column', [FState]
GO

EXEC sp_addextendedproperty 'MS_Description', '提现密码', 'Schema', [dbo], 'table', [TMerchant], 'column', [FWithdrawPwd]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户应用RSA2私钥', 'Schema', [dbo], 'table', [TMerchant], 'column', [FRSA2Key]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户接收通知地址', 'Schema', [dbo], 'table', [TMerchant], 'column', [FRecvNotifyUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '是否同步跳转', 'Schema', [dbo], 'table', [TMerchant], 'column', [FSyncJumpUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '代付用户组', 'Schema', [dbo], 'table', [TMerchant], 'column', [FDFUserGroup]
GO


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TMerchantChannel', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户通道', 'SCHEMA', 'dbo', 'table', 'TMerchantChannel' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户通道', 'SCHEMA', 'dbo', 'table', 'TMerchantChannel' 
end


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TMerchantExtend', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户扩展表', 'SCHEMA', 'dbo', 'table', 'TMerchantExtend' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户扩展表', 'SCHEMA', 'dbo', 'table', 'TMerchantExtend' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FAccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户名', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FMName]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户地址', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FAddress]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户身份证号码', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FId_card]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户姓名', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FFullName]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户电话', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FPhone]
GO

EXEC sp_addextendedproperty 'MS_Description', '手机号码', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FMobile]
GO

EXEC sp_addextendedproperty 'MS_Description', '邮政编码', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FPostcode]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户网址', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FStieUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', 'QQ账号', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FQQ]
GO

EXEC sp_addextendedproperty 'MS_Description', 'MSN账号', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FMSN]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后登陆IP地址', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FLastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FLastLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '提现密码', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FWithdrawPwd]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户描述', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FRemark]
GO

EXEC sp_addextendedproperty 'MS_Description', '谷哥验证器密钥', 'Schema', [dbo], 'table', [TMerchantExtend], 'column', [FGoogleSecretKey]
GO


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '全部订单表', 'SCHEMA', 'dbo', 'table', 'TOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '全部订单表', 'SCHEMA', 'dbo', 'table', 'TOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [TOrder], 'column', [FMOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户ID', 'Schema', [dbo], 'table', [TOrder], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [TOrder], 'column', [FFromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道类型', 'Schema', [dbo], 'table', [TOrder], 'column', [FChannelType]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道代码', 'Schema', [dbo], 'table', [TOrder], 'column', [FChannelCode]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [TOrder], 'column', [FAmount]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单状态', 'Schema', [dbo], 'table', [TOrder], 'column', [FState]
GO

EXEC sp_addextendedproperty 'MS_Description', '通知地址', 'Schema', [dbo], 'table', [TOrder], 'column', [FNotifyUrl]
GO


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TPaySetting', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '支付接口配置', 'SCHEMA', 'dbo', 'table', 'TPaySetting' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '支付接口配置', 'SCHEMA', 'dbo', 'table', 'TPaySetting' 
end

EXEC sp_addextendedproperty 'MS_Description', '应用私钥，用于加签提交支付参数', 'Schema', [dbo], 'table', [TPaySetting], 'column', [FPrivateKey]
GO

EXEC sp_addextendedproperty 'MS_Description', '第三方平台公钥，用于验签第三方回调通知参数', 'Schema', [dbo], 'table', [TPaySetting], 'column', [FPublicKey]
GO

EXEC sp_addextendedproperty 'MS_Description', '邮箱地址', 'Schema', [dbo], 'table', [TPaySetting], 'column', [FEmail]
GO

EXEC sp_addextendedproperty 'MS_Description', '重定向地址', 'Schema', [dbo], 'table', [TPaySetting], 'column', [FRedirectUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '256个字节字符串扩展字段，用于存放特殊的支付类型Json数据', 'Schema', [dbo], 'table', [TPaySetting], 'column', [FExtened]
GO


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TPercentage', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户提成比例表', 'SCHEMA', 'dbo', 'table', 'TPercentage' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户提成比例表', 'SCHEMA', 'dbo', 'table', 'TPercentage' 
end


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TRefundOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '退款订单', 'SCHEMA', 'dbo', 'table', 'TRefundOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '退款订单', 'SCHEMA', 'dbo', 'table', 'TRefundOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '实际退款金额', 'Schema', [dbo], 'table', [TRefundOrder], 'column', [FRefundAmount]
GO


GO 
IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'TSuccessOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '成功订单', 'SCHEMA', 'dbo', 'table', 'TSuccessOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '成功订单', 'SCHEMA', 'dbo', 'table', 'TSuccessOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '订单号', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FOderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FMOrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单状态', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FState]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FFromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道类型', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FChannelType]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道代码', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FChannelCode]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FAmount]
GO

EXEC sp_addextendedproperty 'MS_Description', '通知地址', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FNotifyUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付宝Id', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FAlipayId]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单商户比例', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FPercentage]
GO

EXEC sp_addextendedproperty 'MS_Description', '冻结时间', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FFrozenTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '冻结状态', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FFrozenState]
GO

EXEC sp_addextendedproperty 'MS_Description', '退款状态', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FRefundState]
GO

EXEC sp_addextendedproperty 'MS_Description', '退款时间', 'Schema', [dbo], 'table', [TSuccessOrder], 'column', [FRefundTime]
GO
