/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 20-10月-2018 17:53:32 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Account]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Admin]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Admin]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_AdminLoginLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_AdminLoginLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_AdminOperationLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_AdminOperationLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_ChannelGroup]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_ChannelGroup]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Customer]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Customer]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_CustomerLoginLog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_CustomerLoginLog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfFailureOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfFailureOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfSetting]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfSetting]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_DfSuccessOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_DfSuccessOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_FailureOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_FailureOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Merchant]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Merchant]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_MerchantChannel]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_MerchantChannel]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_MerchantExtend]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_MerchantExtend]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_NotifyTicket]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_NotifyTicket]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Order]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Order]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_PaySetting]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_PaySetting]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_Percentage]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_Percentage]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_RefundOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_RefundOrder]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[T_SuccessOrder]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [T_SuccessOrder]
GO

/* Create Tables */

CREATE TABLE [T_Account]
(
	[Id] bigint NOT NULL,    -- 账号Id
	[Name] varchar(50) NOT NULL,
	[Password] varchar(32) NOT NULL,
	[Emai] varchar(50) NULL,
	[Type] int NOT NULL,
	[SecretProblem] int NOT NULL,
	[SecretAnswer] int NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Admin]
(
	[AccountId] bigint NOT NULL,    -- 账号Id
	[JobNumber] int NOT NULL,    -- 工号
	[FirstLoginIp] varchar(32) NULL,    -- 第一次登陆IP
	[LastLoginIp] varchar(32) NULL,    -- 最后一次登陆IP
	[FirstLoginTime] datetime NOT NULL,    -- 第一次登陆时间
	[LastLoginTime] datetime NOT NULL,    -- 最后一次登陆时间
	[CreateTime] datetime NOT NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_AdminLoginLog]
(
	[Id] bigint NOT NULL,
	[AccountId] bigint NOT NULL,
	[LoginIP] varchar(20) NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_AdminOperationLog]
(
	[Id] bigint NOT NULL,
	[AccountId] bigint NULL,
	[LogType] int NOT NULL,
	[LogContent] varchar(1024) NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_ChannelGroup]
(
	[Id] bigint NOT NULL,
	[GroupName] varchar(50) NOT NULL,    -- 分组名
	[GroupType] bigint NOT NULL,    -- 通道分组类型
	[Channels] varchar(1024) NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Customer]
(
	[AccountId] bigint NOT NULL,    -- 账号Id
	[JobNumber] int NOT NULL,    -- 工号
	[FullName] nvarchar(10) NULL,    -- 姓名
	[FirstLoginIp] varchar(20) NULL,    -- 第一次登陆IP
	[LastLoginIp] varchar(20) NULL,    -- 最后一次登陆IP
	[FirstLoginTime] datetime NOT NULL,    -- 第一次登陆时间
	[LastLoginTime] datetime NOT NULL,    -- 最后一次登陆时间
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[FUpdateBy] bigint NULL
)
GO

CREATE TABLE [T_CustomerLoginLog]
(
	[Id] bigint NOT NULL,
	[AccountId] bigint NULL,
	[LoginIP] varchar(20) NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfFailureOrder]
(
	[OrderNum] bigint NOT NULL,
	[MNum] varchar(64) NOT NULL,
	[MId] int NOT NULL,
	[FromIP] varchar(20) NULL,
	[ChannelType] int NOT NULL,
	[ChannelCode] varchar(20) NOT NULL,
	[Amount] decimal(18) NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfOrder]
(
	[OrderNum] bigint NOT NULL,
	[MNum] varchar(64) NOT NULL,
	[MId] int NOT NULL,
	[FromIP] varchar(20) NULL,
	[ChannelType] int NOT NULL,
	[ChannelCode] varchar(20) NOT NULL,
	[Amount] decimal(18) NOT NULL,
	[State] int NOT NULL,
	[NotifyUrl] varchar(128) NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfSetting]
(
	[Id] bigint NOT NULL,
	[SId] varchar(20) NULL,
	[PrivateKey] varchar(2048) NULL,
	[PublicKey] varchar(1024) NULL,
	[PayType] int NOT NULL,
	[Email] varchar(64) NULL,
	[RedirectUrl] varchar(256) NULL,
	[Extened] varchar(256) NULL,
	[LastInfo] varchar(max) NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_DfSuccessOrder]
(
	[OderNum] bigint NOT NULL,
	[MNum] varchar(64) NOT NULL,
	[MId] int NOT NULL,
	[State] bit NOT NULL,
	[FromIP] varchar(20) NULL,
	[ChannelType] int NOT NULL,
	[ChannelCode] varchar(20) NOT NULL,
	[Amount] decimal(18) NOT NULL,
	[NotifyState] int NOT NULL,
	[NotifyUrl] varchar(128) NOT NULL,
	[AlipayId] varchar(10) NULL,
	[Percentage] decimal(18) NOT NULL,
	[FrozenTime] datetime NULL,
	[FrozenState] int NOT NULL,
	[RefundState] int NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_FailureOrder]
(
	[OrderNum] bigint NOT NULL,    -- 订单号
	[MNum] varchar(64) NOT NULL,    -- 商户订单号
	[FMId] int NOT NULL,    -- 商户Id
	[FromIP] varchar(20) NULL,    -- 支付IP
	[ChannelType] int NOT NULL,
	[ChannelCode] varchar(20) NOT NULL,
	[Amount] decimal(18) NOT NULL,    -- 订单金额
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Merchant]
(
	[AccountId] bigint NOT NULL,
	[Mid] int NOT NULL,    -- 商户号
	[PayeeName] nvarchar(20) NULL,    -- 收款人姓名
	[BankName] nvarchar(20) NULL,    -- 开户行
	[BankCard] varchar(18) NULL,    -- 开户银行账号
	[BankAddress] varchar(32) NULL,    -- 开户银行支行
	[AmountTotal] decimal(18) NOT NULL,    -- 结算总额
	[State] int NULL,    -- 商户状态
	[WithdrawPwd] varchar(6) NOT NULL,    -- 提现密码
	[RSA2Key] varchar(2048) NOT NULL,    -- 商户应用RSA2私钥
	[RecvNotifyUrl] varchar(256) NULL,    -- 商户接收通知地址
	[SyncJumpUrl] bit NOT NULL,    -- 是否同步跳转
	[DFUserGroup] int NOT NULL,    -- 代付用户组
	[CreateTime] datetime NULL,
	[CreateBy] int NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] int NULL
)
GO

CREATE TABLE [T_MerchantChannel]
(
	[AccountId] bigint NOT NULL,
	[Mid] int NOT NULL,
	[Channels] varchar(1024) NULL,
	[ChannelGroups] varchar(256) NULL,
	[CreateTime] datetime NULL,
	[CreateBy] int NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] int NULL
)
GO

CREATE TABLE [T_MerchantExtend]
(
	[AccountId] bigint NOT NULL,    -- 账号Id
	[MId] int NOT NULL,    -- 商户Id
	[MName] varchar(20) NOT NULL,    -- 商户名
	[Address] nvarchar(128) NULL,    -- 商户地址
	[Id_Card] varchar(20) NULL,    -- 商户身份证号码
	[FullName] nvarchar(20) NULL,    -- 商户姓名
	[Phone] varchar(20) NULL,    -- 商户电话
	[Mobile] varchar(20) NULL,    -- 手机号码
	[Postcode] varchar(8) NULL,    -- 邮政编码
	[StieUrl] varchar(128) NULL,    -- 商户网址
	[QQ] varchar(16) NULL,    -- QQ账号
	[MSN] varchar(32) NULL,    -- MSN账号
	[LastLoginIp] varchar(20) NULL,    -- 最后登陆IP地址
	[LastLoginTime] datetime NULL,    -- 最后一次登陆时间
	[WithdrawPwd] varchar(6) NOT NULL,    -- 提现密码
	[Remark] varchar(50) NULL,    -- 商户描述
	[GoogleSecretKey] varchar(32) NULL,    -- 谷哥验证器密钥
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_NotifyTicket]
(
	[Id] bigint NOT NULL,
	[OrderNum] bigint NOT NULL,
	[State] int NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Order]
(
	[OrderNum] bigint NOT NULL,
	[MNum] varchar(64) NOT NULL,    -- 商户订单号
	[MId] int NOT NULL,    -- 商户ID
	[FromIP] varchar(20) NULL,    -- 支付IP
	[ChannelType] int NOT NULL,    -- 通道类型
	[ChannelCode] varchar(20) NOT NULL,    -- 通道代码
	[Amount] decimal(18) NOT NULL,    -- 订单金额
	[State] int NOT NULL,    -- 订单状态
	[NotifyUrl] varchar(128) NOT NULL,    -- 通知地址
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] int NULL
)
GO

CREATE TABLE [T_PaySetting]
(
	[Id] bigint NOT NULL,
	[SId] varchar(20) NULL,
	[PrivateKey] varchar(2048) NULL,    -- 应用私钥，用于加签提交支付参数
	[PublicKey] varchar(1024) NULL,    -- 第三方平台公钥，用于验签第三方回调通知参数
	[PayType] int NOT NULL,
	[Email] varchar(64) NULL,    -- 邮箱地址
	[RedirectUrl] varchar(256) NULL,    -- 重定向地址
	[Extened] varchar(50) NULL,    -- 256个字节字符串扩展字段，用于存放特殊的支付类型Json数据
	[LastInfo] varchar(max) NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_Percentage]
(
	[AccountId] bigint NOT NULL,
	[Percentage] decimal(18) NOT NULL,
	[ChannelType] int NOT NULL,
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_RefundOrder]
(
	[OderNum] bigint NOT NULL,
	[MNum] varchar(64) NOT NULL,
	[MId] int NOT NULL,
	[Amount] decimal(18) NOT NULL,
	[RefundType] int NOT NULL,
	[RefundCharge] decimal(18) NOT NULL,
	[RefundAmount] decimal(18) NOT NULL,    -- 实际退款金额
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

CREATE TABLE [T_SuccessOrder]
(
	[OderNum] bigint NOT NULL,    -- 订单号
	[MNum] varchar(64) NOT NULL,    -- 商户订单号
	[MId] int NOT NULL,    -- 商户Id
	[State] bit NOT NULL,    -- 订单状态
	[FromIP] varchar(20) NULL,    -- 支付IP
	[ChannelType] int NOT NULL,    -- 通道类型
	[ChannelCode] varchar(20) NOT NULL,    -- 通道代码
	[Amount] decimal(18) NOT NULL,    -- 订单金额
	[NotifyState] bit NOT NULL,
	[NotifyUrl] varchar(128) NOT NULL,    -- 通知地址
	[AlipayId] varchar(10) NULL,    -- 支付宝Id
	[Percentage] decimal(18) NOT NULL,    -- 订单商户比例
	[FrozenTime] datetime NULL,    -- 冻结时间
	[FrozenState] int NOT NULL,    -- 冻结状态
	[RefundState] int NOT NULL,    -- 退款状态
	[RefundTime] datetime NULL,    -- 退款时间
	[CreateTime] datetime NULL,
	[CreateBy] bigint NULL,
	[UpdateTime] datetime NULL,
	[UpdateBy] bigint NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [T_Account] 
 ADD CONSTRAINT [PK_TAccount]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Admin] 
 ADD CONSTRAINT [PK_TAdmin]
	PRIMARY KEY CLUSTERED ([AccountId] ASC)
GO

ALTER TABLE [T_AdminLoginLog] 
 ADD CONSTRAINT [PK_TAdminLoginLog]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_AdminOperationLog] 
 ADD CONSTRAINT [PK_TAdminOperationLog]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_ChannelGroup] 
 ADD CONSTRAINT [PK_T_ChannelGroup]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Customer] 
 ADD CONSTRAINT [PK_TCustomer]
	PRIMARY KEY CLUSTERED ([AccountId] ASC)
GO

ALTER TABLE [T_CustomerLoginLog] 
 ADD CONSTRAINT [PK_TCustomerLoginLog]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_DfFailureOrder] 
 ADD CONSTRAINT [PK_TDFFailureOrder]
	PRIMARY KEY CLUSTERED ([OrderNum] ASC)
GO

ALTER TABLE [T_DfOrder] 
 ADD CONSTRAINT [PK_T_DfOrder]
	PRIMARY KEY CLUSTERED ([OrderNum] ASC)
GO

ALTER TABLE [T_DfSetting] 
 ADD CONSTRAINT [PK_TDFSetting]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_DfSuccessOrder] 
 ADD CONSTRAINT [PK_TDFSuccessOrder]
	PRIMARY KEY CLUSTERED ([OderNum] ASC)
GO

ALTER TABLE [T_FailureOrder] 
 ADD CONSTRAINT [PK_TFailureOrder]
	PRIMARY KEY CLUSTERED ([OrderNum] ASC)
GO

ALTER TABLE [T_Merchant] 
 ADD CONSTRAINT [PK_TMerchant]
	PRIMARY KEY CLUSTERED ([AccountId] ASC)
GO

ALTER TABLE [T_MerchantChannel] 
 ADD CONSTRAINT [PK_TMerchantChannel]
	PRIMARY KEY CLUSTERED ([AccountId] ASC)
GO

ALTER TABLE [T_MerchantExtend] 
 ADD CONSTRAINT [PK_TMerchantExtend]
	PRIMARY KEY CLUSTERED ([AccountId] ASC)
GO

ALTER TABLE [T_NotifyTicket] 
 ADD CONSTRAINT [PK_T_NotifyTicket]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Order] 
 ADD CONSTRAINT [PK_TOrder]
	PRIMARY KEY CLUSTERED ([OrderNum] ASC)
GO

ALTER TABLE [T_PaySetting] 
 ADD CONSTRAINT [PK_TPaySetting]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [T_Percentage] 
 ADD CONSTRAINT [PK_TPercentage]
	PRIMARY KEY CLUSTERED ([AccountId] ASC)
GO

ALTER TABLE [T_RefundOrder] 
 ADD CONSTRAINT [PK_TRefundOrder]
	PRIMARY KEY CLUSTERED ([OderNum] ASC)
GO

ALTER TABLE [T_SuccessOrder] 
 ADD CONSTRAINT [PK_T_SuccessOrder]
	PRIMARY KEY CLUSTERED ([OderNum] ASC)
GO

/* Create Table Comments */


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Account', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '账号表', 'SCHEMA', 'dbo', 'table', 'T_Account' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '账号表', 'SCHEMA', 'dbo', 'table', 'T_Account' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_Account], 'column', [Id]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Admin', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员表', 'SCHEMA', 'dbo', 'table', 'T_Admin' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员表', 'SCHEMA', 'dbo', 'table', 'T_Admin' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_Admin], 'column', [AccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '工号', 'Schema', [dbo], 'table', [T_Admin], 'column', [JobNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆IP', 'Schema', [dbo], 'table', [T_Admin], 'column', [FirstLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆IP', 'Schema', [dbo], 'table', [T_Admin], 'column', [LastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆时间', 'Schema', [dbo], 'table', [T_Admin], 'column', [FirstLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [T_Admin], 'column', [LastLoginTime]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_AdminLoginLog', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员登陆日志', 'SCHEMA', 'dbo', 'table', 'T_AdminLoginLog' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员登陆日志', 'SCHEMA', 'dbo', 'table', 'T_AdminLoginLog' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_AdminOperationLog', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '管理员操作日志', 'SCHEMA', 'dbo', 'table', 'T_AdminOperationLog' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '管理员操作日志', 'SCHEMA', 'dbo', 'table', 'T_AdminOperationLog' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_ChannelGroup', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '通道组', 'SCHEMA', 'dbo', 'table', 'T_ChannelGroup' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '通道组', 'SCHEMA', 'dbo', 'table', 'T_ChannelGroup' 
end

EXEC sp_addextendedproperty 'MS_Description', '分组名', 'Schema', [dbo], 'table', [T_ChannelGroup], 'column', [GroupName]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道分组类型', 'Schema', [dbo], 'table', [T_ChannelGroup], 'column', [GroupType]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Customer', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '客服表', 'SCHEMA', 'dbo', 'table', 'T_Customer' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '客服表', 'SCHEMA', 'dbo', 'table', 'T_Customer' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_Customer], 'column', [AccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '工号', 'Schema', [dbo], 'table', [T_Customer], 'column', [JobNumber]
GO

EXEC sp_addextendedproperty 'MS_Description', '姓名', 'Schema', [dbo], 'table', [T_Customer], 'column', [FullName]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆IP', 'Schema', [dbo], 'table', [T_Customer], 'column', [FirstLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆IP', 'Schema', [dbo], 'table', [T_Customer], 'column', [LastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '第一次登陆时间', 'Schema', [dbo], 'table', [T_Customer], 'column', [FirstLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [T_Customer], 'column', [LastLoginTime]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfFailureOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付失败订单', 'SCHEMA', 'dbo', 'table', 'T_DfFailureOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付失败订单', 'SCHEMA', 'dbo', 'table', 'T_DfFailureOrder' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付全部订单', 'SCHEMA', 'dbo', 'table', 'T_DfOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付全部订单', 'SCHEMA', 'dbo', 'table', 'T_DfOrder' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfSetting', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '代付接口配置', 'SCHEMA', 'dbo', 'table', 'T_DfSetting' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '代付接口配置', 'SCHEMA', 'dbo', 'table', 'T_DfSetting' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_DfSuccessOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '成功代付订单', 'SCHEMA', 'dbo', 'table', 'T_DfSuccessOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '成功代付订单', 'SCHEMA', 'dbo', 'table', 'T_DfSuccessOrder' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_FailureOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '失败订单', 'SCHEMA', 'dbo', 'table', 'T_FailureOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '失败订单', 'SCHEMA', 'dbo', 'table', 'T_FailureOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '订单号', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [OrderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [MNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FMId]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [FromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [T_FailureOrder], 'column', [Amount]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Merchant', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户表', 'SCHEMA', 'dbo', 'table', 'T_Merchant' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户表', 'SCHEMA', 'dbo', 'table', 'T_Merchant' 
end

EXEC sp_addextendedproperty 'MS_Description', '商户号', 'Schema', [dbo], 'table', [T_Merchant], 'column', [Mid]
GO

EXEC sp_addextendedproperty 'MS_Description', '收款人姓名', 'Schema', [dbo], 'table', [T_Merchant], 'column', [PayeeName]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户行', 'Schema', [dbo], 'table', [T_Merchant], 'column', [BankName]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户银行账号', 'Schema', [dbo], 'table', [T_Merchant], 'column', [BankCard]
GO

EXEC sp_addextendedproperty 'MS_Description', '开户银行支行', 'Schema', [dbo], 'table', [T_Merchant], 'column', [BankAddress]
GO

EXEC sp_addextendedproperty 'MS_Description', '结算总额', 'Schema', [dbo], 'table', [T_Merchant], 'column', [AmountTotal]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户状态', 'Schema', [dbo], 'table', [T_Merchant], 'column', [State]
GO

EXEC sp_addextendedproperty 'MS_Description', '提现密码', 'Schema', [dbo], 'table', [T_Merchant], 'column', [WithdrawPwd]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户应用RSA2私钥', 'Schema', [dbo], 'table', [T_Merchant], 'column', [RSA2Key]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户接收通知地址', 'Schema', [dbo], 'table', [T_Merchant], 'column', [RecvNotifyUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '是否同步跳转', 'Schema', [dbo], 'table', [T_Merchant], 'column', [SyncJumpUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '代付用户组', 'Schema', [dbo], 'table', [T_Merchant], 'column', [DFUserGroup]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_MerchantChannel', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户通道', 'SCHEMA', 'dbo', 'table', 'T_MerchantChannel' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户通道', 'SCHEMA', 'dbo', 'table', 'T_MerchantChannel' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_MerchantExtend', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户扩展表', 'SCHEMA', 'dbo', 'table', 'T_MerchantExtend' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户扩展表', 'SCHEMA', 'dbo', 'table', 'T_MerchantExtend' 
end

EXEC sp_addextendedproperty 'MS_Description', '账号Id', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [AccountId]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [MId]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户名', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [MName]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户地址', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [Address]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户身份证号码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [Id_Card]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户姓名', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [FullName]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户电话', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [Phone]
GO

EXEC sp_addextendedproperty 'MS_Description', '手机号码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [Mobile]
GO

EXEC sp_addextendedproperty 'MS_Description', '邮政编码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [Postcode]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户网址', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [StieUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', 'QQ账号', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [QQ]
GO

EXEC sp_addextendedproperty 'MS_Description', 'MSN账号', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [MSN]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后登陆IP地址', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [LastLoginIp]
GO

EXEC sp_addextendedproperty 'MS_Description', '最后一次登陆时间', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [LastLoginTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '提现密码', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [WithdrawPwd]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户描述', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [Remark]
GO

EXEC sp_addextendedproperty 'MS_Description', '谷哥验证器密钥', 'Schema', [dbo], 'table', [T_MerchantExtend], 'column', [GoogleSecretKey]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_NotifyTicket', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '异步通知记录表', 'SCHEMA', 'dbo', 'table', 'T_NotifyTicket' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '异步通知记录表', 'SCHEMA', 'dbo', 'table', 'T_NotifyTicket' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Order', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '全部订单表', 'SCHEMA', 'dbo', 'table', 'T_Order' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '全部订单表', 'SCHEMA', 'dbo', 'table', 'T_Order' 
end

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [T_Order], 'column', [MNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户ID', 'Schema', [dbo], 'table', [T_Order], 'column', [MId]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [T_Order], 'column', [FromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道类型', 'Schema', [dbo], 'table', [T_Order], 'column', [ChannelType]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道代码', 'Schema', [dbo], 'table', [T_Order], 'column', [ChannelCode]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [T_Order], 'column', [Amount]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单状态', 'Schema', [dbo], 'table', [T_Order], 'column', [State]
GO

EXEC sp_addextendedproperty 'MS_Description', '通知地址', 'Schema', [dbo], 'table', [T_Order], 'column', [NotifyUrl]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_PaySetting', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '支付接口配置', 'SCHEMA', 'dbo', 'table', 'T_PaySetting' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '支付接口配置', 'SCHEMA', 'dbo', 'table', 'T_PaySetting' 
end

EXEC sp_addextendedproperty 'MS_Description', '应用私钥，用于加签提交支付参数', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [PrivateKey]
GO

EXEC sp_addextendedproperty 'MS_Description', '第三方平台公钥，用于验签第三方回调通知参数', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [PublicKey]
GO

EXEC sp_addextendedproperty 'MS_Description', '邮箱地址', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [Email]
GO

EXEC sp_addextendedproperty 'MS_Description', '重定向地址', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [RedirectUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '256个字节字符串扩展字段，用于存放特殊的支付类型Json数据', 'Schema', [dbo], 'table', [T_PaySetting], 'column', [Extened]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_Percentage', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '商户提成比例表', 'SCHEMA', 'dbo', 'table', 'T_Percentage' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '商户提成比例表', 'SCHEMA', 'dbo', 'table', 'T_Percentage' 
end


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_RefundOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '退款订单', 'SCHEMA', 'dbo', 'table', 'T_RefundOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '退款订单', 'SCHEMA', 'dbo', 'table', 'T_RefundOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '实际退款金额', 'Schema', [dbo], 'table', [T_RefundOrder], 'column', [RefundAmount]
GO


GO 
 IF exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'T_SuccessOrder', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', '成功订单', 'SCHEMA', 'dbo', 'table', 'T_SuccessOrder' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', '成功订单', 'SCHEMA', 'dbo', 'table', 'T_SuccessOrder' 
end

EXEC sp_addextendedproperty 'MS_Description', '订单号', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [OderNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户订单号', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [MNum]
GO

EXEC sp_addextendedproperty 'MS_Description', '商户Id', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [MId]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单状态', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [State]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付IP', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FromIP]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道类型', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [ChannelType]
GO

EXEC sp_addextendedproperty 'MS_Description', '通道代码', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [ChannelCode]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单金额', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [Amount]
GO

EXEC sp_addextendedproperty 'MS_Description', '通知地址', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [NotifyUrl]
GO

EXEC sp_addextendedproperty 'MS_Description', '支付宝Id', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [AlipayId]
GO

EXEC sp_addextendedproperty 'MS_Description', '订单商户比例', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [Percentage]
GO

EXEC sp_addextendedproperty 'MS_Description', '冻结时间', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FrozenTime]
GO

EXEC sp_addextendedproperty 'MS_Description', '冻结状态', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [FrozenState]
GO

EXEC sp_addextendedproperty 'MS_Description', '退款状态', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [RefundState]
GO

EXEC sp_addextendedproperty 'MS_Description', '退款时间', 'Schema', [dbo], 'table', [T_SuccessOrder], 'column', [RefundTime]
GO
